---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?user=root&password=root
    username: root
    password: root
  jpa:
    show-sql: true    
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update

adapter:
  winningList: http://INV-ADAPTER/api/inv-query/winningList

cron:
  scheduling: 
    QueryWinningListTask: 0 35 * * * ?
