---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?user=root&password=root
    username: root
    password: root
  jpa:
    show-sql: true    
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  rabbitmq:
    host: 35.237.60.245
    port: 5672
    username: admin
    password: 1qaz2wsx  
  cloud: 
    bus:
      trace.enabled: false   
      
adapter:
  name: INV-ADAPTER
  qryInvHeader: /api/inv-query/qryInvHeader
  
env:
  server: qryInvHeader(local)      
