---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?user=root&password=root
    username: root
    password: root
  jpa:
    show-sql: true    
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  
env:
  server: LOCAL

adapter:
  serverUrl: http://inv-adapter/api/inv-query
  carrierInvChk: /carrierInvChk
  winningList: /winningList
  
mock:
  users: 1|richard|3J0002|/B27.PO2|ieoasl2180&
  
#最大连接数
http: 
  maxTotal: 100
#并发数
  defaultMaxPerRoute: 20
#创建连接的最长时间
  connectTimeout: 1000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
#数据传输的最长时间
  socketTimeout: 10000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true