#spring.datasource.url = jdbc:mysql://192.168.16.62:3306/cf_5ab47bce_6d48_410f_b640_118b7cd5b424?user=KCvGEfKr3SvrjUXe&password=bT6lGm08Gkv5oEkj
#spring.datasource.username = KCvGEfKr3SvrjUXe
#spring.datasource.password = bT6lGm08Gkv5oEkj
---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?user=root&password=root
    username: root
    password: root
  jpa:
    show-sql: true    
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update

env:
  server: LOCAL

http:
  invUrl: //inv-adapter/api/inv-query/winningList/
  
mock:
  users: 1|richard|3J0002|/B27.PO2|ieoasl2180&

  

