---
env:
  server: LOCAL

mof:
  appID: EINV2201806210615
  appKey: NE5RWTRnbDRzTzl1alB1ZQ==
  serverUrl: https://api.einvoice.nat.gov.tw
  api: 
    QryWinningList: /PB2CAPIVAN/invapp/InvApp
    qryInvHeader: /PB2CAPIVAN/invapp/InvApp
    carrierInvChk: /PB2CAPIVAN/invServ/InvServ
    qryCarrierAgg: /PB2CAPIVAN/Carrier/Aggregate
    qryInvDetail: /PB2CAPIVAN/invapp/InvApp
    carrierInvDetail: /PB2CAPIVAN/invServ/InvServ
#最大连接数
http: 
  maxTotal: 100
#并发数
  defaultMaxPerRoute: 20
#创建连接的最长时间
  connectTimeout: 1000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
#数据传输的最长时间
  socketTimeout: 10000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

management.endpoints.web.exposure.include: '*'